import os
from dotenv import load_dotenv

load_dotenv(override=True)

APPLICATION_PATH= os.getenv("APPLICATION_PATH")
CHALLENGE_URL= os.getenv("CHALLENGE_URL")
API_URL= os.getenv("API_URL")
A360_PERSONAL_EMAIL= os.getenv("A360_PERSONAL_EMAIL")
A360_PERSONAL_SERVICE= os.getenv("A360_PERSONAL_SERVICE")
A360_PERSONAL_USER_NAME_SERVICE= os.getenv("A360_PERSONAL_USER_NAME_SERVICE")
FILE_PATH= os.getenv("FILE_PATH")
FILE_PATH_SHEET= os.getenv("FILE_PATH_SHEET")

DATABASE_HOST= os.getenv("DATABASE_HOST")
DATABASE_NAME= os.getenv("DATABASE_NAME")
DATABASE_TABLE= os.getenv("DATABASE_TABLE")
DATABASE_USER= os.getenv("DATABASE_USER")
DATABASE_SERVICE= os.getenv("DATABASE_SERVICE")
DATABASE_USER_NAME_SERVICE= os.getenv("DATABASE_USER_NAME_SERVICE")

COUNTRY= os.getenv("COUNTRY")
DEPARTMENT= os.getenv("DEPARTMENT")
PROCESS_NAME= os.getenv("PROCESS_NAME")